# Generated by Django 2.2.7 on 2019-11-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('personColor', models.CharField(default='', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('from_name', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=100)),
                ('to_name', models.CharField(max_length=100)),
                ('to_email', models.EmailField(max_length=100)),
                ('body_plain', models.TextField()),
                ('body_html', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply_persons', models.ManyToManyField(related_name='outgoingemail', to='mails.Person')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('from_name', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=100)),
                ('to_name', models.CharField(max_length=100)),
                ('to_email', models.EmailField(max_length=100)),
                ('body_plain', models.TextField()),
                ('body_html', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply_persons', models.ManyToManyField(related_name='incomingemail', to='mails.Person')),
            ],
        ),
    ]
