# Generated by Django 2.2.7 on 2019-11-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='reply_persons',
            field=models.ManyToManyField(related_name='incomingemails', to='mails.Person'),
        ),
        migrations.AlterField(
            model_name='outgoingemail',
            name='reply_persons',
            field=models.ManyToManyField(related_name='outgoingemails', to='mails.Person'),
        ),
    ]
