# Generated by Django 2.2.7 on 2019-11-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20191116_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_Super_Person',
            field=models.BooleanField(default=False),
        ),
    ]
