# Generated by Django 2.2.7 on 2019-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_person_is_super_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wait_to_reply',
            field=models.ManyToManyField(related_name='incomingemails', to='mails.IncomingEmail'),
        ),
    ]
