# Generated by Django 2.2.7 on 2019-11-18 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_person_wait_to_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('95797300-dec0-4679-bde9-68c61abd4e64'), max_length=50),
        ),
    ]
