# Generated by Django 2.2.7 on 2019-11-18 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_person_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='from_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('7d20d41b-c895-4d55-8786-61698fe04932'), max_length=50),
        ),
    ]
