# Generated by Django 2.2.7 on 2019-11-18 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_auto_20191118_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('a598c675-93e7-4504-9690-8514df2562a1'), max_length=50),
        ),
    ]
