# Generated by Django 2.2.7 on 2019-11-18 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_auto_20191118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='from_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomingemail',
            name='to_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='outgoingemail',
            name='to_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('fe0d08c9-ec6b-411b-a32f-d21114512c93'), max_length=50),
        ),
    ]
