# Generated by Django 2.2.7 on 2019-11-19 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0010_auto_20191118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('6d48d25f-5a39-4aa8-87d6-06c06f9b16b8'), max_length=50),
        ),
    ]
