# Generated by Django 2.2.7 on 2019-11-19 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0011_auto_20191119_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('e6f0bcc1-4fc7-4a2a-9d0f-439f9bdeb17f'), max_length=50),
        ),
    ]
