# Generated by Django 2.2.7 on 2019-11-21 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0014_auto_20191121_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingemail',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('3c5336d3-a683-442c-bf03-ad2e9751312e'), max_length=50),
        ),
    ]
