# Generated by Django 2.2.7 on 2019-11-21 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0016_auto_20191121_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('e8ba95c6-c5e9-4110-b173-b1dc70e04b62'), max_length=50),
        ),
    ]
