# Generated by Django 2.2.7 on 2019-11-21 14:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0018_auto_20191121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(default=uuid.UUID('44e3b8aa-5699-4e43-8350-4352763004e8'), max_length=50),
        ),
    ]
